version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    depends_on:
      - web
    volumes:
      - /etc/nginx/sites-enabled/kriptoindex.conf:/etc/nginx/conf.d/kriptoindex.conf
      - certbot-webroot:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-webroot:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
  certbot-webroot:
